#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  solenoid,       sensorDigitalOut)
#pragma config(Sensor, dgtl2,  left_lift_encoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  left_drive_encoder, sensorQuadEncoder)
#pragma config(Sensor, dgtl11, right_drive_encoder, sensorQuadEncoder)
#pragma config(Motor,  port1,           left_forward_drive_motor, tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           left_back_top_drive_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           left_back_bottom_drive_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           right_back_top_drive_motor, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           right_back_bottom_drive_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           left_top_lift_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           left_bottom_lift_motor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           right_top_lift_motor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           right_bottom_lift_motor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right_forward_drive_motor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
//what

//Competition Control and Duration Settingsas
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
#include "lift.h"
#include "drive.h"
#include "autonomous.h"
#include "PresetHeights.h"

void pre_auton()
{
	resetDriveEncoders();

}


task autonomous()
{
	setSol(0);
wait1Msec(200);
setMotors(60,60);
wait1Msec(800);
setMotors(0,0);
wait1Msec(200);
setSol(1);
wait1Msec(200);
setMotors(-80,80);
wait1Msec(1400);
setMotors(60,60);
wait1Msec(900);
setMotors(0,0);
wait1Msec(300);
setSol(0);
wait1Msec(200);
setMotors(-60,-60);
wait1Msec(1000);

}

task usercontrol()
{
	resetDriveEncoders();
	resetLiftencoders();
	clearLCDLine(0);
	clearLCDLine(1);






	while (true)
	{
		sprintf(string1, "%d", SensorValue[left_drive_encoder]);
		displayLCDCenteredString(0, string1);
		sprintf(string2, "%d", SensorValue[right_drive_encoder]);
		displayLCDCenteredString(1, string2);

		//methods
		updateOI();
		drive();
		lift();
		clawPiston();


	}
}
